#!/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3.9
"""pydroid 3"""

import requests
import sys
if sys.argv == [sys.argv[0]]:
     print("usage: " + sys.argv[0] + " [url]")
     exit()
a = requests.get(sys.argv[1])
print(a) 
print(a.text)
